#!/bin/bash

# Initialization Script for CKAD Lab
# This script prepares the environment for all lab questions
# Run this after cloning the repository in Killercoda

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
QUESTIONS_DIR="$SCRIPT_DIR/questions"

echo "🚀 Initializing CKAD Lab Environment..."
echo ""

# Make all setup and validate scripts executable
echo "📝 Making all scripts executable..."
find "$QUESTIONS_DIR" -name "*.sh" -type f -exec chmod +x {} \;
echo "✅ All scripts are now executable"
echo ""

# Create helper functions for each question
echo "🔧 Creating environment variables and helper functions..."
echo ""

# Source the functions file or create it
FUNCTIONS_FILE="$SCRIPT_DIR/.lab-functions.sh"

cat > "$FUNCTIONS_FILE" << FUNCTIONS_EOF
# CKAD Lab Helper Functions
# This file is automatically generated by init.sh

# Function to run setup for a question
exec-lab() {
    local lab_num="\$1"
    if [ -z "\$lab_num" ]; then
        echo "Usage: exec-lab <number>"
        echo "Example: exec-lab 01"
        return 1
    fi
    
    # Set QUESTIONS_DIR if not already set
    if [ -z "\$QUESTIONS_DIR" ]; then
        # Try multiple strategies to find questions directory
        local found=false
        
        # Strategy 1: Check if QUESTIONS_DIR is already in environment (from bashrc)
        # (This won't help if not set, but good to check)
        
        # Strategy 2: Try to find relative to common locations
        for base_dir in "\$(pwd)" "\$HOME" "\$HOME/ckad" "/root" "/root/ckad"; do
            if [ -d "\${base_dir}/questions" ]; then
                export QUESTIONS_DIR="\${base_dir}/questions"
                found=true
                break
            elif [ -d "\${base_dir}/ckad/questions" ]; then
                export QUESTIONS_DIR="\${base_dir}/ckad/questions"
                found=true
                break
            fi
        done
        
        # Strategy 3: Try to find from function file location (if source'd from repo)
        if [ "\$found" = false ] && [ -n "\${BASH_SOURCE[0]}" ]; then
            local func_file="\${BASH_SOURCE[0]}"
            if [ -f "\$func_file" ]; then
                local script_dir="\$(cd "\$(dirname "\$func_file")" && pwd 2>/dev/null || pwd)"
                if [ -d "\${script_dir}/questions" ]; then
                    export QUESTIONS_DIR="\${script_dir}/questions"
                    found=true
                elif [ -d "\${script_dir}/../questions" ]; then
                    export QUESTIONS_DIR="\$(cd "\${script_dir}/.." && pwd)/questions"
                    found=true
                fi
            fi
        fi
        
        if [ "\$found" = false ]; then
            echo "❌ Could not find questions directory."
            echo "   Please run init.sh from the repository root or set QUESTIONS_DIR environment variable."
            echo "   Example: export QUESTIONS_DIR=\$(pwd)/questions"
            return 1
        fi
    fi
    
    # Format lab number (01, 02, etc.)
    lab_num=\$(printf "%02d" "\$lab_num" 2>/dev/null || echo "\$lab_num")
    
    # Remove leading zero if exists for directory name (question-1, question-2, etc.)
    local dir_num=\${lab_num#0}
    local lab_dir="\${QUESTIONS_DIR}/question-\${dir_num}"
    
    if [ ! -d "\$lab_dir" ]; then
        echo "❌ Lab question-\${dir_num} not found in \$QUESTIONS_DIR!"
        echo "   Looking for: \$lab_dir"
        return 1
    fi
    
    echo "🚀 Setting up lab question-\${dir_num}..."
    cd "\$lab_dir" || return 1
    ./setup.sh
}

# Function to validate a question
check-lab() {
    local lab_num="\$1"
    if [ -z "\$lab_num" ]; then
        echo "Usage: check-lab <number>"
        echo "Example: check-lab 01"
        return 1
    fi
    
    # Set QUESTIONS_DIR if not already set
    if [ -z "\$QUESTIONS_DIR" ]; then
        # Try multiple strategies to find questions directory
        local found=false
        
        # Strategy 1: Check if QUESTIONS_DIR is already in environment (from bashrc)
        # (This won't help if not set, but good to check)
        
        # Strategy 2: Try to find relative to common locations
        for base_dir in "\$(pwd)" "\$HOME" "\$HOME/ckad" "/root" "/root/ckad"; do
            if [ -d "\${base_dir}/questions" ]; then
                export QUESTIONS_DIR="\${base_dir}/questions"
                found=true
                break
            elif [ -d "\${base_dir}/ckad/questions" ]; then
                export QUESTIONS_DIR="\${base_dir}/ckad/questions"
                found=true
                break
            fi
        done
        
        # Strategy 3: Try to find from function file location (if source'd from repo)
        if [ "\$found" = false ] && [ -n "\${BASH_SOURCE[0]}" ]; then
            local func_file="\${BASH_SOURCE[0]}"
            if [ -f "\$func_file" ]; then
                local script_dir="\$(cd "\$(dirname "\$func_file")" && pwd 2>/dev/null || pwd)"
                if [ -d "\${script_dir}/questions" ]; then
                    export QUESTIONS_DIR="\${script_dir}/questions"
                    found=true
                elif [ -d "\${script_dir}/../questions" ]; then
                    export QUESTIONS_DIR="\$(cd "\${script_dir}/.." && pwd)/questions"
                    found=true
                fi
            fi
        fi
        
        if [ "\$found" = false ]; then
            echo "❌ Could not find questions directory."
            echo "   Please run init.sh from the repository root or set QUESTIONS_DIR environment variable."
            echo "   Example: export QUESTIONS_DIR=\$(pwd)/questions"
            return 1
        fi
    fi
    
    # Format lab number (01, 02, etc.)
    lab_num=\$(printf "%02d" "\$lab_num" 2>/dev/null || echo "\$lab_num")
    
    # Remove leading zero if exists for directory name (question-1, question-2, etc.)
    local dir_num=\${lab_num#0}
    local lab_dir="\${QUESTIONS_DIR}/question-\${dir_num}"
    
    if [ ! -d "\$lab_dir" ]; then
        echo "❌ Lab question-\${dir_num} not found in \$QUESTIONS_DIR!"
        echo "   Looking for: \$lab_dir"
        return 1
    fi
    
    echo "🔍 Validating lab question-\${dir_num}..."
    cd "\$lab_dir" || return 1
    ./validate.sh
}
FUNCTIONS_EOF

# Export QUESTIONS_DIR for functions to use
export QUESTIONS_DIR="$QUESTIONS_DIR"

# Add to bashrc/zshrc if not already there
SHELL_CONFIG=""
if [ -f "$HOME/.bashrc" ]; then
    SHELL_CONFIG="$HOME/.bashrc"
elif [ -f "$HOME/.zshrc" ]; then
    SHELL_CONFIG="$HOME/.zshrc"
elif [ -f "$HOME/.profile" ]; then
    SHELL_CONFIG="$HOME/.profile"
fi

if [ -n "$SHELL_CONFIG" ]; then
    if ! grep -q "CKAD Lab Helper Functions" "$SHELL_CONFIG" 2>/dev/null; then
        echo "📝 Adding functions to $SHELL_CONFIG..."
        cat >> "$SHELL_CONFIG" << EOF

# CKAD Lab Helper Functions (auto-generated by init.sh)
# Set default QUESTIONS_DIR (functions will auto-detect if not set)
export QUESTIONS_DIR="$QUESTIONS_DIR"
[ -f "$FUNCTIONS_FILE" ] && source "$FUNCTIONS_FILE"
EOF
        echo "✅ Functions added to $SHELL_CONFIG"
    else
        # Update QUESTIONS_DIR if it exists but might be outdated
        if grep -q "export QUESTIONS_DIR=" "$SHELL_CONFIG" 2>/dev/null; then
            # Update the export line
            sed -i.bak "s|export QUESTIONS_DIR=.*|export QUESTIONS_DIR=\"$QUESTIONS_DIR\"|" "$SHELL_CONFIG" 2>/dev/null || \
            sed -i "s|export QUESTIONS_DIR=.*|export QUESTIONS_DIR=\"$QUESTIONS_DIR\"|" "$SHELL_CONFIG" 2>/dev/null || true
        fi
        echo "ℹ️  Functions already in $SHELL_CONFIG (updated QUESTIONS_DIR)"
    fi
fi

# Always source in current session to make functions available immediately
echo "🔄 Loading functions in current session..."
export QUESTIONS_DIR="$QUESTIONS_DIR"
source "$FUNCTIONS_FILE" 2>/dev/null || true

# Verify functions are loaded
if type exec-lab &> /dev/null && type check-lab &> /dev/null; then
    echo "✅ Functions loaded successfully!"
else
    echo "⚠️  Functions may not be loaded. Try: source $FUNCTIONS_FILE"
fi

# Create aliases for current session
export exec_lab_01="cd $QUESTIONS_DIR/question-001 && ./setup.sh"
export exec_lab_02="cd $QUESTIONS_DIR/question-002 && ./setup.sh"
export exec_lab_03="cd $QUESTIONS_DIR/question-003 && ./setup.sh"
export exec_lab_04="cd $QUESTIONS_DIR/question-004 && ./setup.sh"
export exec_lab_05="cd $QUESTIONS_DIR/question-005 && ./setup.sh"
export exec_lab_06="cd $QUESTIONS_DIR/question-006 && ./setup.sh"
export exec_lab_07="cd $QUESTIONS_DIR/question-007 && ./setup.sh"

export check_lab_01="cd $QUESTIONS_DIR/question-001 && ./validate.sh"
export check_lab_02="cd $QUESTIONS_DIR/question-002 && ./validate.sh"
export check_lab_03="cd $QUESTIONS_DIR/question-003 && ./validate.sh"
export check_lab_04="cd $QUESTIONS_DIR/question-004 && ./validate.sh"
export check_lab_05="cd $QUESTIONS_DIR/question-005 && ./validate.sh"
export check_lab_06="cd $QUESTIONS_DIR/question-006 && ./validate.sh"
export check_lab_07="cd $QUESTIONS_DIR/question-007 && ./validate.sh"

echo ""
echo "✅ Environment initialized successfully!"
echo ""
echo "📋 Available commands:"
echo ""
echo "   Setup labs:"
echo "     exec-lab 01    or  cd questions/question-001 && ./setup.sh"
echo "     exec-lab 02    or  cd questions/question-002 && ./setup.sh"
echo "     exec-lab 03    or  cd questions/question-003 && ./setup.sh"
echo "     exec-lab 04    or  cd questions/question-004 && ./setup.sh"
echo "     exec-lab 05    or  cd questions/question-005 && ./setup.sh"
    echo "     exec-lab 06    or  cd questions/question-006 && ./setup.sh"
    echo "     exec-lab 07    or  cd questions/question-007 && ./setup.sh"
echo ""
echo "   Validate labs:"
echo "     check-lab 01   or  cd questions/question-001 && ./validate.sh"
echo "     check-lab 02   or  cd questions/question-002 && ./validate.sh"
echo "     check-lab 03   or  cd questions/question-003 && ./validate.sh"
echo "     check-lab 04   or  cd questions/question-004 && ./validate.sh"
echo "     check-lab 05   or  cd questions/question-005 && ./validate.sh"
    echo "     check-lab 06   or  cd questions/question-006 && ./validate.sh"
    echo "     check-lab 07   or  cd questions/question-007 && ./validate.sh"
echo ""
echo "💡 Tip: Use 'exec-lab <number>' and 'check-lab <number>' from anywhere!"
echo "💡 Or use the exported variables: \$exec_lab_01, \$check_lab_01, etc."


