#!/bin/bash

# Initialization Script for CKAD Lab
# This script prepares the environment for all lab questions
# Run this after cloning the repository in Killercoda

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
QUESTIONS_DIR="$SCRIPT_DIR/questions"

echo "🚀 Initializing CKAD Lab Environment..."
echo ""

# Make all setup and validate scripts executable
echo "📝 Making all scripts executable..."
find "$QUESTIONS_DIR" -name "*.sh" -type f -exec chmod +x {} \;
echo "✅ All scripts are now executable"
echo ""

# Create helper functions for each question
echo "🔧 Creating environment variables and helper functions..."
echo ""

# Source the functions file or create it
FUNCTIONS_FILE="$SCRIPT_DIR/.lab-functions.sh"

cat > "$FUNCTIONS_FILE" << 'FUNCTIONS_EOF'
# CKAD Lab Helper Functions
# This file is automatically generated by init.sh

# Function to run setup for a question
exec-lab() {
    local lab_num="$1"
    if [ -z "$lab_num" ]; then
        echo "Usage: exec-lab <number>"
        echo "Example: exec-lab 01"
        return 1
    fi
    
    # Format lab number (01, 02, etc.)
    lab_num=$(printf "%02d" "$lab_num" 2>/dev/null || echo "$lab_num")
    
    local lab_dir="${QUESTIONS_DIR}/question-${lab_num#0}"
    
    if [ ! -d "$lab_dir" ]; then
        echo "❌ Lab question-${lab_num#0} not found!"
        return 1
    fi
    
    echo "🚀 Setting up lab question-${lab_num#0}..."
    cd "$lab_dir"
    ./setup.sh
}

# Function to validate a question
check-lab() {
    local lab_num="$1"
    if [ -z "$lab_num" ]; then
        echo "Usage: check-lab <number>"
        echo "Example: check-lab 01"
        return 1
    fi
    
    # Format lab number (01, 02, etc.)
    lab_num=$(printf "%02d" "$lab_num" 2>/dev/null || echo "$lab_num")
    
    local lab_dir="${QUESTIONS_DIR}/question-${lab_num#0}"
    
    if [ ! -d "$lab_dir" ]; then
        echo "❌ Lab question-${lab_num#0} not found!"
        return 1
    fi
    
    echo "🔍 Validating lab question-${lab_num#0}..."
    cd "$lab_dir"
    ./validate.sh
}
FUNCTIONS_EOF

# Source the functions
export QUESTIONS_DIR="$QUESTIONS_DIR"
source "$FUNCTIONS_FILE"

# Add to bashrc/zshrc if not already there
SHELL_CONFIG=""
if [ -f "$HOME/.bashrc" ]; then
    SHELL_CONFIG="$HOME/.bashrc"
elif [ -f "$HOME/.zshrc" ]; then
    SHELL_CONFIG="$HOME/.zshrc"
elif [ -f "$HOME/.profile" ]; then
    SHELL_CONFIG="$HOME/.profile"
fi

if [ -n "$SHELL_CONFIG" ]; then
    if ! grep -q "CKAD Lab Helper Functions" "$SHELL_CONFIG" 2>/dev/null; then
        echo "📝 Adding functions to $SHELL_CONFIG..."
        cat >> "$SHELL_CONFIG" << EOF

# CKAD Lab Helper Functions
export QUESTIONS_DIR="$QUESTIONS_DIR"
source "$FUNCTIONS_FILE" 2>/dev/null || true
EOF
        echo "✅ Functions added to $SHELL_CONFIG"
    else
        echo "ℹ️  Functions already in $SHELL_CONFIG"
    fi
fi

# Create aliases for current session
export exec_lab_01="cd $QUESTIONS_DIR/question-001 && ./setup.sh"
export exec_lab_02="cd $QUESTIONS_DIR/question-002 && ./setup.sh"
export exec_lab_03="cd $QUESTIONS_DIR/question-003 && ./setup.sh"
export exec_lab_04="cd $QUESTIONS_DIR/question-004 && ./setup.sh"
export exec_lab_05="cd $QUESTIONS_DIR/question-005 && ./setup.sh"
export exec_lab_06="cd $QUESTIONS_DIR/question-006 && ./setup.sh"

export check_lab_01="cd $QUESTIONS_DIR/question-001 && ./validate.sh"
export check_lab_02="cd $QUESTIONS_DIR/question-002 && ./validate.sh"
export check_lab_03="cd $QUESTIONS_DIR/question-003 && ./validate.sh"
export check_lab_04="cd $QUESTIONS_DIR/question-004 && ./validate.sh"
export check_lab_05="cd $QUESTIONS_DIR/question-005 && ./validate.sh"
export check_lab_06="cd $QUESTIONS_DIR/question-006 && ./validate.sh"

echo ""
echo "✅ Environment initialized successfully!"
echo ""
echo "📋 Available commands:"
echo ""
echo "   Setup labs:"
echo "     exec-lab 01    or  cd questions/question-001 && ./setup.sh"
echo "     exec-lab 02    or  cd questions/question-002 && ./setup.sh"
echo "     exec-lab 03    or  cd questions/question-003 && ./setup.sh"
echo "     exec-lab 04    or  cd questions/question-004 && ./setup.sh"
echo "     exec-lab 05    or  cd questions/question-005 && ./setup.sh"
echo "     exec-lab 06    or  cd questions/question-006 && ./setup.sh"
echo ""
echo "   Validate labs:"
echo "     check-lab 01   or  cd questions/question-001 && ./validate.sh"
echo "     check-lab 02   or  cd questions/question-002 && ./validate.sh"
echo "     check-lab 03   or  cd questions/question-003 && ./validate.sh"
echo "     check-lab 04   or  cd questions/question-004 && ./validate.sh"
echo "     check-lab 05   or  cd questions/question-005 && ./validate.sh"
echo "     check-lab 06   or  cd questions/question-006 && ./validate.sh"
echo ""
echo "💡 Tip: Use 'exec-lab <number>' and 'check-lab <number>' from anywhere!"
echo "💡 Or use the exported variables: \$exec_lab_01, \$check_lab_01, etc."


